// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:vocaber/models/dailystat.dart';
import 'package:vocaber/models/word.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DailyStatAdapter());
    registerAdapter(WordAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DailyStatAdapter());
    registerAdapter(WordAdapter());
  }
}
